<?php
/**
 * Dc_GoogleTranslateWidget
 * 
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Dc
 * @package    Dc_GoogleTranslateWidget
 * @copyright  Copyright (c) 2013-2015 Damián Culotta. (http://www.damianculotta.com.ar/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($this->isEnabled()): ?>
    <div id="google_translate_element"></div>
    <script type="text/javascript">
    function googleTranslateElementInit() {
        new google.translate.TranslateElement({
            pageLanguage: '<?php echo $this->getPageLanguage(); ?>'
            <?php if ($this->getSpecificLanguages()): ?>,includedLanguages: '<?php echo $this->getLanguages(); ?>'<?php endif; ?>
            <?php if ($this->getDisplay()): ?><?php echo $this->getDisplay(); ?><?php endif; ?>
            <?php if ($this->isMultilanguage()): ?>,multilanguagePage: true<?php endif; ?>
            <?php if ($this->useGA()): ?>,gaTrack: true, gaId: '<?php echo $this->getGACode(); ?>'<?php endif; ?>
        },'google_translate_element');
    }
    </script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<?php endif; ?>
